### ISSUE TITLE
Howto use this from Saxon (or from within oXygen XML)

### ISSUE THREAD

**Issue by cwittern** [expath/expath-http-client-java#13]
Hi, 
I need to POST a request from a XSLT script, so it seems this is the library I need.  I now spend a few days looking for information on the Web, but most of it seems to be outdated and does not work.  A concise explanation on how to install this library for use with Saxon, or within oXygen would be highly appreciated!

**Comment by adamretter** [comment]
@cwittern I just updated the README.md with more info. The Saxon wrapper was inherited from @fgeorges and I haven't tested it manually. Let me know how you get on and feel free to send a PR to further improve the README.md.

**Comment by cwittern** [comment]
Dear Adam, thank you for your help, once more.  I will report any further problems.

**Comment by cwittern** [comment]
OK, I am still trying to solve this problem.  I have put all of Saxon's jar files, as well as the two jar files from this project (expath-pkg-saxon-0.15.0.jar and expath-tools-saxon-0.3.0.jar) into a directory and set the classpath to point here like this:
`export CLASSPATH="/home/chris/00scratch/saxon/*"`
next, I have added the extension function to the configuration file as indicated in the Readme (using PE, but this should also work, yes?):
`<configuration xmlns="http://saxon.sf.net/ns/configuration"
               edition="PE"
               licenseFileLocation="saxon-license.lic"
               label="Some label">
  <global
      traceExternalFunctions="true"/>
  <resources>
    <extensionFunction>org.expath.httpclient.saxon.SendRequestFunction</extensionFunction>
  </resources>
</configuration>`
When I try to run this on the commandline, I get this:
`java net.sf.saxon.Transform -config:config.xml -s:ret.xml -xsl:collate.xsl
Warning on line 9 column 91 of config.xml:
   Invalid configuration property extensionFunction. Supplied value
  'org.expath.httpclient.saxon.SendRequestFunction', required value is the name of a class
  that implements 'net.sf.saxon.lib.ExtensionFunctionDefinition'. Caused by
  net.sf.saxon.trans.XPathException: Failed to load
  org.expath.httpclient.saxon.SendRequestFunction. Caused by
  java.lang.ClassNotFoundException: org.expath.httpclient.saxon.SendRequestFunction
Invalid configuration property extensionFunction. Supplied value 'org.expath.httpclient.saxon.SendRequestFunction', required value is the name of a class that implements 'net.sf.saxon.lib.ExtensionFunctionDefinition'
`
collate.xsl imports expath-client-saxon.xsl, which contains this:
`<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:http="http://expath.org/ns/http-client"
                xmlns:java="java:org.expath.saxon.HttpClient"
                version="3.0">
   <xsl:function name="http:send-request" as="item()+">
      <xsl:param name="request" as="element(http:request)?"/>
      <xsl:sequence select="java:send-request($request)"/>
   </xsl:function>
`
and collate.xsl makes a call to http:send-request. 
What I do not understand is why the extension function is not found.  Any help is appreciated.

**Comment by adamretter** [comment]
I think the error indicates that your classpath is wrong.

> export CLASSPATH="/home/chris/00scratch/saxon/*"
I don't think you can use a `*` here

Unfortunately there are quite a lot of Jar files that you will need to add to the classpath. To simplify this I have added two things:

## 1. A small application for testing
After running `mvn package` you will now find a folder `http-client-saxon/target/http-client-saxon-1.2.5-SNAPSHOT-dir`. In that folder is a `bin/` folder with some scripts which will run Saxon with the classpath setup for all the Jar files in the `lib/` folder. This uses Saxon-HE.

So you can for example run this:
```
bin/transform.sh -config:config.xml -s:input1.xml -xsl:example1.xslt
```

To call the EXPath HTTP Client, my `example1.xslt` looks like this:
```xml
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:http="http://expath.org/ns/http-client"
    exclude-result-prefixes="xs"
    version="2.0">
    
    <xsl:template match="/">
        <xsl:variable name="my-request" as="element(http:request)">
            <http:request href='http://www.adamretter.org.uk' method='get'/>
        </xsl:variable>
        <xsl:copy-of select="http:send-request($my-request)"/>
    </xsl:template>
    
</xsl:stylesheet>
```

## 2. An Uber jar for the Saxon EXPath Http Client
After running `mvn package` you will now find a file: `http-client-saxon/target/http-client-saxon-1.2.5-SNAPSHOT-uber.jar`.

This is a single Jar file that includes all the dependencies (apart from Saxon). You can use it with Saxon like so (assuming the two Jars are in the same folder that you run `java` from):

```
java -classpath http-client-saxon-1.2.5-SNAPSHOT-uber.jar:Saxon-HE-9.7.0-15.jar net.sf.saxon.Transform -config:config.xml -s:input1.xml -xsl:example1.xslt
```

**Comment by OyvindLGjesdal** [comment]
I've had a default way of using extension functions in Oxygen (and command line) by supplying an Initializer with my local extension functions. 

https://www.saxonica.com/html/documentation/javadoc/net/sf/saxon/lib/Initializer.html

Would supplying a default Initializer with the Saxon RI be a way to simplify this? It works for HE,PE and EE editions.

Using http client in Oxygen would then look like:
* Download or build uber jar and add to Transformation Scenario - Edit - Extensions
* Configure Transformation Scenario -> Edit -> Options button next to Transformer select -> Initializer (Class) -> Choose (Looks for implementations in Classpath/ Added Extensions.)

<img width="518" alt="initializer1" src="https://user-images.githubusercontent.com/5328572/96996055-7d041d80-152f-11eb-9f23-58d5b65d2de1.png">
<img width="412" alt="initializer2" src="https://user-images.githubusercontent.com/5328572/96996074-855c5880-152f-11eb-925e-383b41fe69df.png">

Same in command line add:
`-init:initializer org.expath.http.client.ExampleInitializer` and uberjar to Classpath.

example Initializer for my extensions: https://git.app.uib.no/Oyvind.Gjesdal/sef/-/blob/master/src/main/java/no/uib/saxon/ef/SimmetricsInitializer.java
