### ISSUE TITLE
Headers Fail to Get Set When Processing Http:body 

### ISSUE THREAD

**Issue by ajbufort** [expath/expath-http-client-java#51]
Cannot invoke "org.expath.httpclient.HeaderSet.getFirstHeader(String)" because "headers" is null

...is returned by oXygen 26.1 when processing the following XSL...

                    <http:request method="post" default-charset="utf-8">
                        <http:header name="Accept" value="*/*;charset=utf-8"/>
                        <http:header name="Accept-Encoding" value="utf-8"/>
                        <http:header name="Authorization" value="Bearer {$api-key}"/>
                        <http:header name="Content-Type" value="application/json;utf-8"/>
                        
                        <http:body media-type="application/json">
                            {
                            "model": "gpt-3.5-turbo-16k",
                            "messages": [
                            {
                            "role": "system",
                            "content": "You are a helpful assistant."
                            },
                            {
                            "role": "user",
                            "content": "Hello!"
                            }
                            ]
                            }
                        </http:body>
                    </http:request>

This run is using Saxon-EE 12.3 and http-client-saxon-1.5.1-uber.jar.

Elimination of http:body results in a working, but uselsss, run.  So body provokes headers getting set, but it seems that they can't be set because the default variable to which they need to be added isn't an empty array but rather a null.

**Comment by adamretter** [comment]
I just released version 1.5.2 which should fix your issue @ajbufort.

Once comment - this header in your request is invalid: `<http:header name="Content-Type" value="application/json;utf-8"/>` it should be `<http:header name="Content-Type" value="application/json; charset=utf-8"/>`.

Also `<http:body media-type="application/json">` should be `<http:body media-type="text/plain">`

**Comment by adamretter** [comment]
@ajbufort Did this resolve your issue?

**Comment by ajbufort** [comment]
Yes, finally able to test properly again, resolution confirmed.
