### ISSUE TITLE
HTTP Client module namespace prefix doesn't match spec

### ISSUE THREAD

**Issue by joewiz** [expath/expath-http-client-java#6]
The `hc` module namespace prefix is [hardcoded](https://github.com/expath/expath-http-client-java/blob/master/http-client-java/src/main/java/org/expath/httpclient/HttpConstants.java#L21-L22) in the EXPath HTTP Client implementation. However, [the spec](http://expath.org/spec/http-client) makes no mention of an `hc` prefix. The spec clearly defines the namespace prefix as `http`:

> The module defined by this document does define one function in the namespace `http://expath.org/ns/http-client`. In this document, the `http` prefix, when used, is bound to this namespace URI.

This mismatch between the spec and the implementation leads to confusion. For example, eXist ships with http-client and thus should be available without an explicit module import, but invoking the `http:send-request` function triggers the following error:

> Invalid qname http:send-request. No namespace defined for prefix http. QName is invalid: INVALID_PREFIX

This error is only triggered because the namespace prefix bound to the module is `hc` instead of `http`. 

Thus, the implementation should be changed so that the hardcoded namespace prefix conforms with the spec: it should be `http`.

**Comment by fgeorges** [comment]
Hi @joewiz.  Thanks for the ticket.

The prefix is not defined in the spec.  It is only informal ("in this document", "when used").  This prefix in the class is only there to help build an informative prefix, used e.g. in the Saxon implementation.

If eXist defines the namespace for the EXPath HTTP Client functions to be bound to the prefix `http` in the static context, and it is not, I would rather open a ticket there.

As far as I know, eXist comes rather with the version 2 of the HTTP Client, defined there: https://expath.github.io/expath-cg/specs/http-client-2/.

**Comment by joewiz** [comment]
@fgeorges I see your point, thanks. I located where eXist defines the namespace for the EXPath HTTP Client functions to be effectively bound to the `hc` prefix in the static context (which I think is what you meant in your comment), [here](https://github.com/eXist-db/exist/blob/develop/extensions/expath/src/main/java/org/expath/exist/HttpClientModule.java#L37-L39).

To "fix" this, I could submit a PR to the eXist project changing the 2nd line in:

```java
    public final static String NAMESPACE_URI = HttpConstants.HTTP_CLIENT_NS_URI;

    public final static String PREFIX = HttpConstants.HTTP_CLIENT_NS_PREFIX;
```

to this:

```java
    public final static String PREFIX = HttpConstants.HTTP_NS_PREFIX;
```

or perhaps simply:

```java
    public final static String PREFIX = "http";
```

Before I do so, though, could you shed any light on the purpose of `HTTP_NS_PREFIX` and `HTTP_NS_URI`, as defined in https://github.com/expath/expath-http-client-java/blob/master/http-client-java/src/main/java/org/expath/httpclient/HttpConstants.java#L19-L20?  I don't see these variables being used at all, nor is the `"http://expath.org/ns/http"` URI mentioned in the spec.  I'd just like to make sure that there's no problem in repurposing the `http` prefix defined in `HTTP_NS_PREFIX` for the module namespace prefix.

Thanks again!

**Comment by joewiz** [comment]
My PR https://github.com/eXist-db/exist/pull/3041 addresses this issue.

**Comment by fgeorges** [comment]
Thank you, @joewiz.  For the record, to answer your question above:

The "`http`" namespace was reserved for a work we started with @adamretter, once upon a time.  The idea was to define an XML language to represent HTTP entities (requests and responses).  To be used ultimately both in the HTTP Client (a piece of software sending requests and receiving responses) and in Servlex (receiving requests and sending responses back).

These two components define the same thing (and most likely with differences, behind the namespace URI, which is unfortunate).  Unifying these two representations was the right thing to do.  And could have been used in other contexts as well.

Unfortunately, we never went through the full process (I remember having a partial draft at some point.)

**Comment by adamretter** [comment]
Indeed, the idea was to model "http" in XML and keep that in `http://expath.org/ns/http` with the `http` prefix. This model would be independent of the HTTP Client. I also wanted this model for use with RESTXQ.

The HTTP Client functions would have remained in `http://expath.org/ns/http-client` with the `hc` prefix.

As @fgeorges points-out, that effort ultimately stalled.

**Comment by joewiz** [comment]
@fgeorges @adamretter Thank you for explaining the background - "hc" was always such a mystery to me. Seeing as [the draft 2.0 spec](https://expath.github.io/expath-cg/specs/http-client-2/#namespaces-and-prefixes) still uses `http` and again makes no mention of any `hc` or alternative namespace, I think the convention to use the `http` prefix in the spec and, by extension, in implementations like eXist and BaseX (which already uses `http`, not `hc`) makes sense.

**Comment by adamretter** [comment]
@joewiz Yes, for the time being I agree that is the best approach.
